version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
      
  build:
    commands:
       - mvn package

reports: #New
  SurefireReportsUnitTest: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '*.xml'
    base-directory: 'unit-tests/target/surefire-reports' # Location of the reports
  SurefireReportsIntegrationTest: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '*.xml'
    base-directory: 'integration-tests/target/surefire-reports' # Location of the reports
    
artifacts:
  files:
    - application/target/*
    - deployspec.yml
    - manifest.yml